### ISSUE TITLE
Proposal 1 - RedR00t Development Fund

### ISSUE THREAD

**Issue by omniversereality** [genesis-x/proposals#1]
## Requested funds
Ongoing proposal, but voting done in monthly blocks
Month 1 - 50,000 XGS from governance + 15,000 XGS from cold storage dev funds

## Describe your proposal
RedR00t is a core developer behind the SPS and all of its components. This issue will ensure appropriate funding for him to complete the work by expected deadlines.

## What is the proposal about?
Monthly payments being passed through our governance system to ensure RedR00t is paid to a reasonable degree for his efforts.

## How is it going to help the project or the community?
Incentivise him to complete roadmap goals swiftly.

## Proposal creator Discord user
chockblain#7454

**Comment by omniversereality** [comment]
Please leave notes here so as to refine the proposal before submitting!

**Comment by soldatchristi** [comment]
Why not. Let's do it.

**Comment by tooshameless** [comment]
It would be appreciated to see a detailed proposal that included milestones and goals for such an appropriation of funds.

**Comment by soggietoes** [comment]
More details regarding milestones and roadmap would help community with fund allocation

**Comment by omniversereality** [comment]
Putting together details on what this is paying for.

**Comment by genesis-x** [comment]
We are also interested in what you think is a reasonable price to pay for this service to create and maintain the SPS?

**Comment by lilhobbit489** [comment]
I think this would be a wise choice as there is really nothing else pushing people to purchase XGS. This is the sole use case for XGS at the moment. Getting it out to the masses will help drive adoption. Payment in BTC would probably work best for the developer.

**Comment by Arjen83** [comment]
Appropriate funding for the dev is essential but we have weeks now with $500-$1000 24hr vol per day. So paying the dev 65K XGS for one month makes that he wants / need to sell this for a living where the issue is that there is not enough demand to keep de XGS price stable. So selling 65K XGS in the market for one month wihout demand will result in a (significant) price drop which will potentially harm investors in this project. Mabe it's better to pay him in XGS masternodes with a contratct that he can't sell / liquidate during period x. He's incentiviced to keep the masternodes and let the price increase and community / investors will also benefit from this. The dev needs to get an incentive to make te project succesfull and as a result his masternodes and wealth in XGS will increase together with the community. If this is not an option I would think in other payment options such as mentioned above where he's paid in BTC instead of XGS. The project is too young to pay 65K XGS monthly to the dev with an incentive to liquidate te position because he needs it for a living.

**Comment by omniversereality** [comment]
This would not be a monthly payment but a one off. I will see what terms we can all agree too.

**Comment by M1NuTeLaTe11** [comment]
Pay him at the end of each Month  (assuming this goes straight through q4  total's 9 Months)
 (  65k/9 months=7222 XGS per month)                                                                         (7222-5000=2222)                                                               
                If progress is being made give him like a 1 node at the end of every month--^^-so that's 2222 every month that extra 2222 can be used as an incentive for speedy completion of each part.                                                                   
                                    ((((((    (21666XGS=9 months x 2222)===slush fund    )))))
          When smaller parts are completed give him say  1k  of the 21666 (shown above) the bigger the milestone the more you take out of that slush fund and incentive him to finish.   If he misses a deadline he would forfeit his monthly node and incentive...                                                                                                            
           Idk if that makes much sense, but there has to be incentives and consequences.,..... Maybe even make it 4000 a month to raise the incentive slush fund...............**Also, this will clearly have no effect on the price if he sells**                  Just my 0.02 cents

**Comment by genesis-x** [comment]
Hey Rizen, 

I like that idea. The limitation with governance is that once the proposal goes through the timing can't be changed in regards to payout as it was approved. However the funds will go to the core team premine address and then be released from there. So to be assured here it will still be controlled by the core team. When he responds to me with the detail on what he is going to do this may determine the payout. Thanks for the input!

**Comment by genesis-x** [comment]
We will be uploading a document spelling out the additions and features that will be added to the platform in this development in the next 24 hours. Thanks for your patience.

**Comment by omniversereality** [comment]
[GenesisX.pdf](https://github.com/genesis-x/proposals/files/2982764/GenesisX.pdf)
